### PR TITLE
Feature downsize images

### PR DESCRIPTION
**Pull request by n8fr8**
This is working pretty well!

### CODE REVIEW

**Comment by eighthave** [comment]
there were some API changes in cacheword, including removing the notification handling.  I guess that didn't affect chatsecure?  I guess I'm surprised, but I'll check it out in the morning for myself.

**Comment by n8fr8** [comment]
We don't use the cacheword notification so it was not an issue. Still, I
reinstated the submodule commit to the right place.

**Comment by eighthave** [comment]
I think we should keep CacheWord as it is in ChatSecure v14.  There are no new features added in newer cacheword commits, just lots of cruft removed so that cacheword can be used in a project as a single jar.  This pull request doesn't work as is, loading these two commits into Eclipse and building gives me lots and lots of build errors related to CacheWord, here are some of them:
```
CacheWordActivityHandler cannot be resolved to a type	LockScreenActivity.java	/ChatSecure/src/info/guardianproject/otr/app/im/app	line 53	Java Problem
The import info.guardianproject.cacheword.CacheWordActivityHandler cannot be resolved	LockScreenActivity.java	/ChatSecure/src/info/guardianproject/otr/app/im/app	line 29	Java Problem
The method getBlankServiceIntent(Context) is undefined for the type CacheWordService	WelcomeActivity.java	/ChatSecure/src/info/guardianproject/otr/app/im/app	line 553	Java Problem
```

**Comment by n8fr8** [comment]
Sorry for the confusion. I thought I had kept it at the right commit.

**Comment by eighthave** [comment]
I got this working as I described, based on your commit.  So I'm closing this and will open a big merge request for all my recent work.

**Comment by n8fr8** [comment]
Already done! thx.

**Pull request closed without merging**
