### PR TITLE
fixes #677 on github: update asmack to address "sessionSupported" bug

### LINKED ISSUE #677: cannot connect to jabberd2 due to missing
With 14.1.1RC5 on Android 4.4, I cannot log in to xmpp on jabberd 2.3.3.  The problem as discussed on guardian-dev is that the server does not send the session-supported capability, and ChatSecure (really in Smack) errors out.  However, the current protocol spec does not require sending session-supported:

https://tools.ietf.org/html/rfc6121#appendix-E

To fix, update Smack, as this has been fixed:

https://igniterealtime.org/issues/browse/SMACK-379

Smack also copes with problems due to this being optional:

https://igniterealtime.org/issues/browse/SMACK-622

### PR DESCRIPTION
**Pull request by n8fr8**
https://github.com/guardianproject/ChatSecureAndroid/issues/677

### CODE REVIEW

**Comment by n8fr8** [comment]
This is the relevant change in our Smack build:
https://github.com/guardianproject/smack/commit/9935fe65757dd7de8a0f537c7d6c44d08dae75a4

**Comment by eighthave** [comment]
this doesn't update `libs/asmack-android-8.jar`, which is what ChatSecure actually uses when it builds

**Comment by eighthave** [comment]
otherwise, the code change itself seems fine

**Comment by n8fr8** [comment]
It does.. check the "files changed":

 BIN  libs/asmack-android-8.jar

**Comment by eighthave** [comment]
oops, sorry skimmed it too fast...

**Pull request merged**
