### PR TITLE
Linkify n stuff

### PR DESCRIPTION
**Pull request by eighthave**
improved linkifying in the ChatView, including things like:

* geo:49.563374,17.291426?z=8
* @guardianproject
* #fail
* openpgp4fpr:5E61C8780F86295CE17D86779F0FE587374BBE81

Also, this adds a new preference "Linkify on Tor" and changes a default: now, no links are created on chats from accounts that are setup with Tor.  The preference overrides that.

### CODE REVIEW

**Comment by n8fr8** [comment]
All looks good and working well!

**Comment by twzkxkan** [comment]
@eighthave I am looking to add this feature to MAPS.ME, would you be able to advise? The issue tracker is [here](https://github.com/mapsme/omim/issues/803). You may be interested since it is free software and on F-Droid now.

**Comment by eighthave** [comment]
@ghost here is the best example for how a map app can share location in a flexible way:
https://github.com/osmandapp/Osmand/pull/1033

**Comment by eighthave** [comment]
@ghost can you point me to MAPS.ME on f-droid?  I can't find it.

**Comment by ighsiwwx** [comment]
Sorry, it was soon removed due to a [request](https://github.com/mapsme/omim/issues/85#issuecomment-161184745) by MAPS.ME developers. a Development of a fork continues [here](https://github.com/relan/omim).

**Pull request merged**
