### PR TITLE
Bug fix send intent support

### PR DESCRIPTION
**Pull request by n8fr8**
Fixes for sending media from external apps that use content:// URIs and streams, and not files on disk.

Also some additional changes to on/offline notification state of persistent icon, and presence refresh on reconnect.

### CODE REVIEW

**Comment by eighthave** [comment]
everything else looks good

**Comment by n8fr8** [comment]
Changes made based on feedback

**Comment by eighthave** [comment]
The open question is: why would `mNotifyBuilder` be `null` when `networkStateChanged()` is run.  `mNotifyBuilder` is set by `if (mUseForeground) startForegroundCompat();`  So I guess either the notification is only ever shown when `mUseForeground` is `true` and `mNotifyBuilder` should be `null` is correct, otherwise the notification will not be updated if `mUseForeground` is `false`.

**Comment by n8fr8** [comment]
networkStateChanged() is triggered via broadcasts events that can be triggered pretty quickly once the server is setup... meaning, you are getting network events even before you are logged in. We could look at improving that logic.

**Comment by eighthave** [comment]
@n8fr8 when `mUseForeground` is false, are the notifications also supposed to be updated?  Because in the current code, they will not be because `mNotifyBuilder` is only initialized when `mUseForeground` is true.

**Comment by n8fr8** [comment]
they are not, because there is no notification visible when foreground is not on, so it is all good.

**Comment by eighthave** [comment]
what about the "chat received" notification?

**Comment by n8fr8** [comment]
Those are handled elswhere

**Pull request merged**
